title: Xuan Wang
description: Developer · Writer · Photographer
theme: minima
baseurl: "" # leave empty for user pages
url: "https://xuanwgit.github.io"

collections:
  codes:
    output: true
  stories:
    output: true
  visions:
    output: true
