title: Xuan Wang
description: Developer · Writer · Photographer
theme: minima
baseurl: "" # leave empty for user pages
url: "https://xuanwgit.github.io"

sass:
  style: compressed
  sass_dir: _sass

header_pages:
  - index.md
  - codes.md
  - stories.md
  - visions.md
  - about.md

collections:
  codes:
    output: true
  stories:
    output: true
  visions:
    output: true
